/**
 * http://top10000songs.blogspot.com/2012/12/top-10000-songs.html
 */
const musics = [
  "1 Smooth - Santana",
  "2 Mack The Knife - Bobby Darin",
  "3 You Light Up My Life - Debby Boone",
  "4 I Gotta Feeling - Black Eyed Peas, The",
  "5 Hey Jude - Beatles, The",
  "6 How Do I Live - LeAnn Rimes",
  "7 I'm Yours - Jason Mraz",
  "8 Yeah! - Usher",
  "9 Physical - Olivia Newton-John",
  "10 Too Close - Next",
  "11 We Belong Together - Mariah Carey",
  "12 The Theme From \"A Summer Place\" - Percy Faith",
  "13 Party Rock Anthem - LMFAO",
  "14 Raindrops Keep Fallin' On My Head - B.J. Thomas",
  "15 Tossin' And Turnin' - Bobby Lewis",
  "16 I'll Make Love To You - Boyz II Men",
  "17 Bette Davis Eyes - Kim Carnes",
  "18 Tie A Yellow Ribbon Round The Ole Oak Tree - Dawn",
  "19 End Of The Road - Boyz II Men",
  "20 I Want To Hold Your Hand - Beatles, The",
  "21 How You Remind Me - Nickelback",
  "22 Un-Break My Heart - Toni Braxton",
  "23 I Just Want To Be Your Everything - Andy Gibb",
  "24 Truly Madly Deeply - Savage Garden",
  "25 Before He Cheats - Carrie Underwood",
  "26 Every Breath You Take - Police, The",
  "27 Need You Now - Lady Antebellum",
  "28 Endless Love - Diana Ross",
  "29 I'm A Believer - Monkees, The",
  "30 The Battle Of New Orleans - Johnny Horton",
  "31 Sugar, Sugar - Archies, The",
  "32 How Deep Is Your Love - Bee Gees",
  "33 Bust A Move - Young M.C.",
  "34 Hanging By A Moment - Lifehouse",
  "35 Rolling In The Deep - Adele",
  "36 The First Time Ever I Saw Your Face - Roberta Flack",
  "37 Candle In The Wind 1997 - Elton John",
  "38 Low - Flo Rida",
  "39 Call Me - Blondie",
  "40 It's Now Or Never - Elvis Presley",
  "41 Just The Way You Are - Bruno Mars",
  "42 Macarena (Bayside Boys Mix) - Los Del Rio",
  "43 Unwell - matchbox twenty",
  "44 That's What Friends Are For - Dionne & Friends",
  "45 Shadow Dancing - Andy Gibb",
  "46 The Sign - Ace Of Base",
  "47 Joy To The World - Three Dog Night",
  "48 Whoomp! There It Is - Tag Team",
  "49 Amazed - Lonestar",
  "50 Eye Of The Tiger - Survivor",
  "51 Flashdance...What A Feeling - Irene Cara",
  "52 One Sweet Day - Mariah Carey",
  "53 Aquarius/Let The Sunshine In (The Flesh Failures) - 5th Dimension, The",
  "54 Hello, Dolly! - Louis Armstrong",
  "55 Gold Digger - Kanye West",
  "56 The Twist - Chubby Checker",
  "57 Tonight's The Night (Gonna Be Alright) - Rod Stewart",
  "58 Viva La Vida - Coldplay",
  "59 Why Me - Kris Kristofferson",
  "60 Love Will Keep Us Together - Captain and Tennille, The",
  "61 Alone Again (Naturally) - Gilbert O'Sullivan",
  "62 Breathe - Faith Hill",
  "63 Love Is Blue (L'Amour Est Bleu) - Paul Mauriat and His Orchestra",
  "64 (I Can't Get No) Satisfaction - Rolling Stones, The",
  "65 What's Love Got To Do With It - Tina Turner",
  "66 I Can't Stop Loving You - Ray Charles",
  "67 Night Fever - Bee Gees",
  "68 TiK ToK - Ke$ha",
  "69 I'm Sorry - Brenda Lee",
  "70 On My Own - Patti LaBelle",
  "71 Straight Up - Paula Abdul",
  "72 Kryptonite - 3 Doors Down",
  "73 Another One Bites The Dust - Queen",
  "74 Walk Like An Egyptian - Bangles",
  "75 Big Girls Don't Cry - 4 Seasons, The",
  "76 I Will Always Love You - Whitney Houston",
  "77 I Heard It Through The Grapevine - Marvin Gaye",
  "78 Le Freak - Chic",
  "79 Family Affair - Mary J. Blige",
  "80 I'll Be There - Jackson 5",
  "81 You And Me - Lifehouse",
  "82 The Flame - Cheap Trick",
  "83 Love Takes Time - Mariah Carey",
  "84 Big Girls Don't Cry - Fergie",
  "85 Are You Lonesome To-Night? - Elvis Presley",
  "86 How To Save A Life - Fray, The",
  "87 Here Without You - 3 Doors Down",
  "88 Alone - Heart",
  "89 Billie Jean - Michael Jackson",
  "90 The Ballad Of The Green Berets - S/Sgt. Barry Sadler (U.S. Army Special Forces)",
  "91 My Sharona - Knack, The",
  "92 Let Me Love You - Mario",
  "93 To Sir With Love - Lulu",
  "94 Love Story - Taylor Swift",
  "95 Stagger Lee - Lloyd Price",
  "96 (Everything I Do) I Do It For You - Bryan Adams",
  "97 The Way We Were - Barbra Streisand",
  "98 Another Night - Real McCoy",
  "99 Sugar Shack - Jimmy Gilmer",
  "100 American Pie (Parts 1 and 2) - Don McLean",
  "101 Jessie's Girl - Rick Springfield",
  "102 Hey, Soul Sister - Train",
  "103 Centerfold - J. Geils Band, The",
  "104 Oh, Pretty Woman - Roy Orbison",
  "105 Nobody Knows - Tony Rich Project",
  "106 Stayin' Alive - Bee Gees",
  "107 Running Bear - Johnny Preston",
  "108 Total Eclipse Of The Heart - Bonnie Tyler",
  "109 Maggie May - Rod Stewart",
  "110 I'll Be Missing You - Puff Daddy & Faith Evans",
  "111 Foolish - Ashanti",
  "112 Dilemma - Nelly",
  "113 Vision Of Love - Mariah Carey",
  "114 Where My Girls At? - 702",
  "115 You Belong With Me - Taylor Swift",
  "116 Lady - Kenny Rogers",
  "117 Goodies - Ciara",
  "118 Rhinestone Cowboy - Glen Campbell",
  "119 A Fifth Of Beethoven - Walter Murphy",
  "120 Say Say Say - Paul McCartney",
  "121 I Swear - All-4-One",
  "122 Boom Boom Pow - Black Eyed Peas, The",
  "123 I Go Crazy - Paul Davis",
  "124 Smoke Gets In Your Eyes - Platters, The",
  "125 No One - Alicia Keys",
  "126 In Da Club - 50 Cent",
  "127 Nothing Compares 2 U - Sinead O'Connor",
  "128 Silly Love Songs - Wings",
  "129 Money For Nothing - Dire Straits",
  "130 Big Bad John - Jimmy Dean",
  "131 Gangsta's Paradise - Coolio",
  "132 Wind Beneath My Wings - Bette Midler",
  "133 I Can See Clearly Now - Johnny Nash",
  "134 Never Gonna Give You Up - Rick Astley",
  "135 It's Too Late - Carole King",
  "136 Love Theme From A Star Is Born (Evergreen) - Barbra Streisand",
  "137 Another Brick In The Wall (Part II) - Pink Floyd",
  "138 Limbo Rock - Chubby Checker",
  "139 Let's Get It On - Marvin Gaye",
  "140 Drops Of Jupiter - Train",
  "141 He'll Have To Go - Jim Reeves",
  "142 Bridge Over Troubled Water - Simon and Garfunkel",
  "143 When Doves Cry - Prince",
  "144 I Don't Want To Wait - Paula Cole",
  "145 Here I Go Again - Whitesnake",
  "146 Honey - Bobby Goldsboro",
  "147 Since U Been Gone - Kelly Clarkson",
  "148 Don't You Want Me - Human League, The",
  "149 Careless Whisper - Wham!",
  "150 Upside Down - Diana Ross",
  "151 I Think I Love You - Partridge Family, The",
  "152 (They Long To Be) Close To You - Carpenters",
  "153 Missing - Everything But The Girl",
  "154 You Make Me Wanna.. - Usher",
  "155 Unwritten - Natasha Bedingfield",
  "156 This Kiss - Faith Hill",
  "157 Save The Best For Last - Vanessa Williams",
  "158 The Way You Love Me - Faith Hill",
  "159 Livin' On A Prayer - Bon Jovi",
  "160 Gloria - Laura Branigan",
  "161 You've Lost That Lovin' Feelin' - Righteous Brothers, The",
  "162 Best Of My Love - Emotions, The",
  "163 Firework - Katy Perry",
  "164 Irreplaceable - Beyonce",
  "165 Love Machine (Part 1) - Miracles, The",
  "166 Moves Like Jagger - Maroon 5",
  "167 Venus - Frankie Avalon",
  "168 Dynamite - Taio Cruz",
  "169 He's So Fine - Chiffons, The",
  "170 Dreamlover - Mariah Carey",
  "171 Look Away - Chicago",
  "172 Philadelphia Freedom - Elton John",
  "173 Somebody That I Used To Know - Gotye",
  "174 Waterfalls - TLC",
  "175 I Will Survive - Gloria Gaynor",
  "176 ..Baby One More Time - Britney Spears",
  "177 Kiss You All Over - Exile",
  "178 Everyday People - Sly & the Family Stone",
  "179 Winchester Cathedral - New Vaudeville Band, The",
  "180 Turn! Turn! Turn! (To Everything There Is A Season) - Byrds, The",
  "181 Cathy's Clown - Everly Brothers, The",
  "182 Take A Bow - Madonna",
  "183 Baby Got Back - Sir Mix-A-Lot",
  "184 I Wanna Know - Joe",
  "185 Hey Ya! - OutKast",
  "186 Celebration - Kool & The Gang",
  "187 Everybody Wants To Rule The World - Tears For Fears",
  "188 Run It! - Chris Brown",
  "189 Bleeding Love - Leona Lewis",
  "190 Light My Fire - Doors, The",
  "191 Baby Love - Supremes, The",
  "192 Peppermint Twist - Part 1 - Joey Dee & the Starliters",
  "193 Nothing's Gonna Stop Us Now - Starship",
  "194 If I Ain't Got You - Alicia Keys",
  "195 Wonderland By Night - Bert Kaempfert and His Orchestra",
  "196 The Letter - Box Tops, The",
  "197 Bad, Bad Leroy Brown - Jim Croce",
  "198 Killing Me Softly With His Song - Roberta Flack",
  "199 F**K You (Forget You) - Cee Lo Green",
  "200 Jump - Van Halen",
  "201 You're Still The One - Shania Twain",
  "202 Knock Three Times - Dawn",
  "203 I Love Rock 'N Roll - Joan Jett & The Blackhearts",
  "204 She Loves You - Beatles, The",
  "205 The Boy Is Mine - Brandy & Monica",
  "206 Don't Speak - No Doubt",
  "207 We Found Love - Rihanna",
  "208 Breakaway - Kelly Clarkson",
  "209 (Sittin' On) The Dock Of The Bay - Otis Redding",
  "210 Lose Yourself - Eminem",
  "211 Hot Stuff - Donna Summer",
  "212 Gonna Make You Sweat - C & C Music Factory",
  "213 Runaway - Del Shannon",
  "214 Hurts So Good - John Cougar",
  "215 Play That Funky Music - Wild Cherry",
  "216 Feelings - Morris Albert",
  "217 Sweet Child O' Mine - Guns N' Roses",
  "218 How Am I Supposed To Live Without You - Michael Bolton",
  "219 People Got To Be Free - Rascals, The",
  "220 Barely Breathing - Duncan Sheik",
  "221 Rhythm Is A Dancer - Snap!",
  "222 Just Dance - Lady GaGa",
  "223 SexyBack - Justin Timberlake",
  "224 Wherever You Will Go - Calling, The",
  "225 Sexy And I Know It - LMFAO",
  "226 Apologize - Timbaland",
  "227 Cherish - Association, The",
  "228 Vogue - Madonna",
  "229 Heartaches By The Number - Guy Mitchell",
  "230 Somethin' Stupid - Nancy Sinatra",
  "231 The Three Bells - Browns, The",
  "232 Stuck With You - Huey Lewis & The News",
  "233 Dominique - Singing Nun, The",
  "234 Do That To Me One More Time - Captain and Tennille",
  "235 Honky Tonk Women - Rolling Stones, The",
  "236 I Just Called To Say I Love You - Stevie Wonder",
  "237 All Night Long (All Night) - Lionel Richie",
  "238 (Love Is) Thicker Than Water - Andy Gibb",
  "239 Wishing Well - Terence Trent D'Arby",
  "240 Against All Odds (Take A Look At Me Now) - Phil Collins",
  "241 Then Came You - Dionne Warwicke",
  "242 Rush Rush - Paula Abdul",
  "243 Sherry - 4 Seasons, The",
  "244 Ebony And Ivory - Paul McCartney",
  "245 Say You, Say Me - Lionel Richie",
  "246 Dancing Machine - Jackson 5",
  "247 Windy - Association, The",
  "248 All 4 Love - Color Me Badd",
  "249 Stranger On The Shore - Mr. Acker Bilk",
  "250 That's The Way Love Goes - Janet Jackson",
  "251 Kiss And Say Goodbye - Manhattans, The",
  "252 When I'm Gone - 3 Doors Down",
  "253 This Love - Maroon5",
  "254 Down Under - Men At Work",
  "255 Without You - Nilsson",
  "256 Roses Are Red (My Love) - Bobby Vinton",
  "257 I Can't Help Myself - Four Tops",
  "258 My Love - Paul McCartney",
  "259 Run-Around - Blues Traveler",
  "260 The Power Of Love - Celine Dion",
  "261 You're Makin' Me High - Toni Braxton",
  "262 The Way You Move - OutKast",
  "263 In The Year 2525 (Exordium & Terminus) - Zager & Evans",
  "264 (You're My) Soul And Inspiration - Righteous Brothers, The",
  "265 Like A Virgin - Madonna",
  "266 The Most Beautiful Girl - Charlie Rich",
  "267 Use Somebody - Kings Of Leon",
  "268 Seasons In The Sun - Terry Jacks",
  "269 La Bamba - Los Lobos",
  "270 American Woman - Guess Who, The",
  "271 Close To You - Maxi Priest",
  "272 Informer - Snow",
  "273 Jump - Kris Kross",
  "274 Help! - Beatles, The",
  "275 Fallin' - Alicia Keys",
  "276 All That She Wants - Ace Of Base",
  "277 Exodus - Ferrante and Teicher",
  "278 Need You Tonight - INXS",
  "279 Lonely Boy - Paul Anka",
  "280 Rock With You - Michael Jackson",
  "281 You're So Vain - Carly Simon",
  "282 (Just Like) Starting Over - John Lennon",
  "283 Down - Jay Sean",
  "284 Creep - TLC",
  "285 How Can You Mend A Broken Heart - Bee Gees",
  "286 Bad Day - Daniel Powter",
  "287 I Need To Know - Marc Anthony",
  "288 The Candy Man - Sammy Davis Jr.",
  "289 Independent Women Part I - Destiny's Child",
  "290 Baby Boy - Beyoncé",
  "291 This Guy's In Love With You - Herb Alpert",
  "292 We Are Young - Fun.",
  "293 A Lover's Question - Clyde McPhatter",
  "294 Abracadabra - Steve Miller Band, The",
  "295 Just Another Day - Jon Secada",
  "296 Can't Help Falling In Love - UB40",
  "297 I Get Around - Beach Boys, The",
  "298 Save The Last Dance For Me - Drifters, The",
  "299 December 1963 (Oh, What A Night) - Four Seasons, The",
  "300 Bad Girls - Donna Summer",
  "301 Everything You Want - Vertical Horizon",
  "302 It Must Have Been Love - Roxette",
  "303 You Don't Have To Be A Star (To Be In My Show) - Marilyn McCoo & Billy Davis Jr.",
  "304 El Paso - Marty Robbins",
  "305 Laughter In The Rain - Neil Sedaka",
  "306 Slide - Goo Goo Dolls",
  "307 The Sweet Escape - Gwen Stefani",
  "308 Together Again - Janet",
  "309 There! I've Said It Again - Bobby Vinton",
  "310 Beat It - Michael Jackson",
  "311 Downtown - Petula Clark",
  "312 Hot Child In The City - Nick Gilder",
  "313 Sad Eyes - Robert John",
  "314 Give Me Everything - Pitbull",
  "315 Call Me Maybe - Carly Rae Jepsen",
  "316 It's Been Awhile - StainD",
  "317 Brand New Key - Melanie",
  "318 Crank That (Soulja Boy) - Soulja Boy Tell'em",
  "319 Hot N Cold - Katy Perry",
  "320 Fingertips - Pt 2 - Little Stevie Wonder",
  "321 A Thousand Miles - Vanessa Carlton",
  "322 Right Here Waiting - Richard Marx",
  "323 Hey Paula - Paul and Paula",
  "324 Donna - Ritchie Valens",
  "325 Quit Playing Games (With My Heart) - Backstreet Boys, The",
  "326 Sukiyaki - Kyu Sakamoto",
  "327 Iris - Goo Goo Dolls",
  "328 Blue Velvet - Bobby Vinton",
  "329 Breathe Again - Toni Braxton",
  "330 Burn - Usher",
  "331 Whatever You Like - T.I.",
  "332 Happy Together - Turtles, The",
  "333 Emotions - Mariah Carey",
  "334 Love The Way You Lie - Eminem",
  "335 I Can't Get Next To You - Temptations, The",
  "336 Wild Night - John Mellencamp",
  "337 Glory Of Love (Theme From The Karate Kid Part II) - Peter Cetera",
  "338 We Built This City - Starship",
  "339 Ode To Billie Joe - Bobbie Gentry",
  "340 Love Child - Diana Ross and the Supremes",
  "341 Greatest Love Of All - Whitney Houston",
  "342 Beverly Hills - Weezer",
  "343 Footloose - Kenny Loggins",
  "344 I'll Always Love You - Taylor Dayne",
  "345 Arthur's Theme (Best That You Can Do) - Christopher Cross",
  "346 We Can Work It Out - Beatles, The",
  "347 Daydream Believer - Monkees, The",
  "348 Hot In Herre - Nelly",
  "349 I Write The Songs - Barry Manilow",
  "350 Come See About Me - Supremes, The",
  "351 One Bad Apple - Osmonds, The",
  "352 Believe - Cher",
  "353 Thankyou - Dido",
  "354 Everytime You Go Away - Paul Young",
  "355 Get Back - Beatles, The",
  "356 Mr. Blue - Fleetwoods, The",
  "357 How Will I Know - Whitney Houston",
  "358 Do Ya Think I'm Sexy? - Rod Stewart",
  "359 High Enough - Damn Yankees",
  "360 Before The Next Teardrop Falls - Freddy Fender",
  "361 OMG - Usher",
  "362 Miss You Much - Janet Jackson",
  "363 Baby Don't Get Hooked On Me - Mac Davis",
  "364 Maria, Maria - Santana",
  "365 100x Pure Love - Crystal Waters",
  "366 I Knew I Loved You - Savage Garden",
  "367 I Miss You - Klymaxx",
  "368 I Want You Back - Jackson 5, The",
  "369 My Eyes Adored You - Frankie Valli",
  "370 You Were Meant For Me - Jewel",
  "371 Baby Come Back - Player",
  "372 Dizzy - Tommy Roe",
  "373 With Or Without You - U2",
  "374 Over My Head (Cable Car) - Fray, The",
  "375 Empire State Of Mind - Jay-Z",
  "376 You're Beautiful - James Blunt",
  "377 Nobody's Supposed To Be Here - Deborah Cox",
  "378 Girl You Know It's True - Milli Vanilli",
  "379 Semi-Charmed Life - Third Eye Blind",
  "380 One Hell Of A Woman - Mac Davis",
  "381 Don't Leave Me This Way - Thelma Houston",
  "382 Kung Fu Fighting - Carl Douglas",
  "383 Boogie Oogie Oogie - Taste Of Honey, A",
  "384 Because You Loved Me - Celine Dion",
  "385 Magic - Olivia Newton-John",
  "386 Wooly Bully - Sam the Sham and the Pharaohs",
  "387 Umbrella - Rihanna",
  "388 Wake Me Up Before You Go-Go - Wham!",
  "389 No Scrubs - TLC",
  "390 The Game Of Love - Santana",
  "391 Roll With It - Steve Winwood",
  "392 Waiting On The World To Change - John Mayer",
  "393 Jack & Diane - John Cougar",
  "394 Ignition - R. Kelly",
  "395 Groovin' - Young Rascals",
  "396 Back To Life - Soul II Soul",
  "397 Genie In A Bottle - Christina Aguilera",
  "398 Reach Out I'll Be There - Four Tops",
  "399 My Guy - Mary Wells",
  "400 War - Edwin Starr",
  "401 Please Mr. Postman - Marvelettes, The",
  "402 I Think We're Alone Now - Tiffany",
  "403 Where Do You Go - No Mercy",
  "404 Forever Your Girl - Paula Abdul",
  "405 Come Softly To Me - Fleetwoods, The",
  "406 Monday, Monday - Mamas and The Papas, The",
  "407 Black Velvet - Alannah Myles",
  "408 Hey! Baby - Bruce Channel",
  "409 Where Did Our Love Go - Supremes, The",
  "410 Unpretty - TLC",
  "411 California Gurls - Katy Perry",
  "412 Hero - Mariah Carey",
  "413 How's It Going To Be - Third Eye Blind",
  "414 Coming Up (Live At Glasgow) - Paul McCartney",
  "415 Faith - George Michael",
  "416 Poker Face - Lady GaGa",
  "417 Disturbia - Rihanna",
  "418 Hello - Lionel Richie",
  "419 Crocodile Rock - Elton John",
  "420 I Love A Rainy Night - Eddie Rabbitt",
  "421 Reunited - Peaches & Herb",
  "422 She Will Be Loved - Maroon5",
  "423 Give Me One Reason - Tracy Chapman",
  "424 Ghostbusters - Ray Parker Jr.",
  "425 Come And Get Your Love - Redbone",
  "426 Woman In Love - Barbra Streisand",
  "427 Change The World - Eric Clapton",
  "428 My Sweet Lord - George Harrison",
  "429 Black Or White - Michael Jackson",
  "430 North To Alaska - Johnny Horton",
  "431 Yesterday - Beatles, The",
  "432 I'd Die Without You - PM Dawn",
  "433 Wild, Wild West - Escape Club, The",
  "434 Everybody's Somebody's Fool - Connie Francis",
  "435 This Is How We Do It - Montell Jordan",
  "436 Love Song - Sara Bareilles",
  "437 The Twist - Chubby Checker",
  "438 Hollaback Girl - Gwen Stefani",
  "439 Travelin' Man - Ricky Nelson",
  "440 Promiscuous - Nelly Furtado",
  "441 Super Bass - Nicki Minaj",
  "442 Lean On Me - Bill Withers",
  "443 Love Is Alive - Gary Wright",
  "444 Opposites Attract - Paula Abdul",
  "445 Pop Muzik - M",
  "446 Let's Twist Again - Chubby Checker",
  "447 Keep On Truckin' (Part 1) - Eddie Kendricks",
  "448 Lights - Ellie Goulding",
  "449 If You're Gone - matchbox twenty",
  "450 Finally - Ce Ce Peniston",
  "451 U Got It Bad - Usher",
  "452 Hold On - Wilson Phillips",
  "453 Sweet Dreams (Are Made Of This) - Eurythmics",
  "454 Bubbly - Colbie Caillat",
  "455 You Gotta Be - Des'ree",
  "456 Don't Walk Away - Jade",
  "457 Telstar - Tornadoes, The",
  "458 Baby, Come To Me - Patti Austin",
  "459 Mrs. Brown You've Got A Lovely Daughter - Herman's Hermits",
  "460 Good Feeling - Flo Rida",
  "461 Don't Let Go (Love) - En Vogue",
  "462 Indian Reservation (The Lament Of The Cherokee Reservation Indian) - Raiders, The",
  "463 Get Low - Lil Jon & The East Side Boyz",
  "464 Bent - matchbox twenty",
  "465 Strangers In The Night - Frank Sinatra",
  "466 Chasing Cars - Snow Patrol",
  "467 Midnight Train To Georgia - Gladys Knight and the Pips",
  "468 Sixteen Reasons - Connie Stevens",
  "469 Crazy Little Thing Called Love - Queen",
  "470 Owner Of A Lonely Heart - Yes",
  "471 Lollipop - Lil Wayne",
  "472 Only In My Dreams - Debbie Gibson",
  "473 1, 2 Step - Ciara",
  "474 Check On It - Beyonce",
  "475 I Like Dreamin' - Kenny Nolan",
  "476 I'm Real - Jennifer Lopez",
  "477 One Last Breath - Creed",
  "478 Can't Nobody Hold Me Down - Puff Daddy",
  "479 Angel In Your Arms - Hot",
  "480 Sexy Chick - David Guetta",
  "481 Motownphilly - Boyz II Men",
  "482 On Bended Knee - Boyz II Men",
  "483 Because I Love You (The Postman Song) - Stevie B",
  "484 Boulevard Of Broken Dreams - Green Day",
  "485 Pony Time - Chubby Checker",
  "486 My Lovin' (You're Never Gonna Get It) - En Vogue",
  "487 Islands In The Stream - Kenny Rogers",
  "488 Follow You Down - Gin Blossoms",
  "489 I Will Follow Him - Little Peggy March",
  "490 (You're) Having My Baby - Paul Anka",
  "491 Killing Me Softly - Fugees, The",
  "492 Crazy In Love - Beyoncé",
  "493 We Are The World - USA for Africa",
  "494 Take On Me - A-Ha",
  "495 Fly, Robin, Fly - Silver Convention",
  "496 The Good, The Bad And The Ugly - Hugo Montenegro",
  "497 Mr. Jones - Counting Crows",
  "498 Queen Of Hearts - Juice Newton",
  "499 Disco Lady - Johnnie Taylor",
  "500 Live Your Life - T.I.",
  "501 Three Times A Lady - Commodores",
  "502 Can't Fight This Feeling - REO Speedwagon",
  "503 Shake You Down - Gregory Abbott",
  "504 Wedding Bell Blues - 5th Dimension, The",
  "505 I Got You Babe - Sonny & Cher",
  "506 You Found Me - Fray, The",
  "507 Let It Be - Beatles, The",
  "508 Michael - Highwaymen, The",
  "509 Judy In Disguise (With Glasses) - John Fred and His Playboy Band",
  "510 Anything For You - Gloria Estefan",
  "511 My Boyfriend's Back - Angels, The",
  "512 Top Of The World - Carpenters",
  "513 I Gotcha - Joe Tex",
  "514 Back At One - Brian McKnight",
  "515 Fame - David Bowie",
  "516 Kiss From A Rose - Seal",
  "517 Soldier Boy - Shirelles, The",
  "518 Crimson And Clover - Tommy James and the Shondells",
  "519 The First Time - Surface",
  "520 Sunshine Of Your Love - Cream, The",
  "521 My Love - Justin Timberlake",
  "522 Shake Ya Tailfeather - Nelly",
  "523 You're The One That I Want - John Travolta and Olivia Newton-John",
  "524 96 Tears - ? and the Mysterians",
  "525 Get Ready - Rare Earth",
  "526 Stronger (What Doesn't Kill You) - Kelly Clarkson",
  "527 I Want To Know What Love Is - Foreigner",
  "528 Will It Go Round In Circles - Billy Preston",
  "529 More Than Words - Extreme",
  "530 One Of These Nights - Eagles",
  "531 E.T. - Katy Perry",
  "532 One More Try - Timmy T",
  "533 Family Affair - Sly & The Family Stone",
  "534 Go Away Little Girl - Steve Lawrence",
  "535 The Way I Are - Timbaland",
  "536 I Like The Way (The Kissing Game) - Hi-Five",
  "537 I Love The Nightlife (Disco Round) - Alicia Bridges",
  "538 Someday - Nickelback",
  "539 All My Life - K-Ci & JoJo",
  "540 Get Busy - Sean Paul",
  "541 Teenage Dream - Katy Perry",
  "542 Stay - Lisa Loeb & Nine Stories",
  "543 The First Night - Monica",
  "544 Me And Mrs. Jones - Billy Paul",
  "545 Kiss Me - Sixpence None The Richer",
  "546 Don't Cha - Pussycat Dolls, The",
  "547 Hey There Delilah - Plain White T's",
  "548 Gypsys, Tramps & Thieves - Cher",
  "549 Maneater - Daryl Hall & John Oates",
  "550 My Heart Is An Open Book - Carl Dobkins Jr.",
  "551 Fantasy - Mariah Carey",
  "552 Torn Between Two Lovers - Mary MacGregor",
  "553 Touch Me In The Morning - Diana Ross",
  "554 Don't It Make My Brown Eyes Blue - Crystal Gayle",
  "555 Heart And Soul - T'Pau",
  "556 My Boo - Usher",
  "557 I Know - Dionne Farris",
  "558 I Hope You Dance - Lee Ann Womack",
  "559 Don't Turn Around - Ace Of Base",
  "560 Hands To Heaven - Breathe",
  "561 Keep On Loving You - REO Speedwagon",
  "562 Love's Theme - Love Unlimited Orchestra",
  "563 Don't Go Breaking My Heart - Elton John",
  "564 Come Together - Beatles, The",
  "565 Baby-Baby-Baby - TLC",
  "566 I Know You Want Me (Calle Ocho) - Pitbull",
  "567 Go Away Little Girl - Donny Osmond",
  "568 The Reason - Hoobastank",
  "569 Summer In The City - Lovin' Spoonful, The",
  "570 Kind Of A Drag - Buckinghams, The",
  "571 No Diggity - BLACKstreet",
  "572 Broken Wings - Mr. Mister",
  "573 Stop! In The Name Of Love - Supremes, The",
  "574 Kiss On My List - Daryl Hall & John Oates",
  "575 My Humps - Black Eyed Peas, The",
  "576 I Love You Always Forever - Donna Lewis",
  "577 Sara Smile - Daryl Hall & John Oates",
  "578 Paralyzer - Finger Eleven",
  "579 Missing You - John Waite",
  "580 Who Can It Be Now? - Men At Work",
  "581 Little Green Apples - O.C. Smith",
  "582 Brandy (You're A Fine Girl) - Looking Glass",
  "583 Don't Dream It's Over - Crowded House",
  "584 Ain't No Mountain High Enough - Diana Ross",
  "585 Addicted To Love - Robert Palmer",
  "586 Lost In Your Eyes - Debbie Gibson",
  "587 Crazy For You - Madonna",
  "588 As I Lay Me Down - Sophie B. Hawkins",
  "589 The Tears Of A Clown - Smokey Robinson",
  "590 Higher Love - Steve Winwood",
  "591 Funkytown - Lipps, Inc.",
  "592 Music - Madonna",
  "593 Glad You Came - Wanted, The",
  "594 Baby Baby - Amy Grant",
  "595 He's A Rebel - Crystals, The",
  "596 Lean Back - Terror Squad",
  "597 Mr. Lonely - Bobby Vinton",
  "598 All I Have - Jennifer Lopez",
  "599 Complicated - Avril Lavigne",
  "600 With Arms Wide Open - Creed",
  "601 Someone Like You - Adele",
  "602 Jump Around - House Of Pain",
  "603 A Horse With No Name - America",
  "604 Til I Hear It From You - Gin Blossoms",
  "605 Johnny Angel - Shelley Fabares",
  "606 I'm Your Boogie Man - KC and the Sunshine Band",
  "607 Gives You Hell - All-American Rejects, The",
  "608 Cold Hearted - Paula Abdul",
  "609 Grenade - Bruno Mars",
  "610 Bring Me To Life - Evanescence",
  "611 Chapel Of Love - Dixie Cups, The",
  "612 Will You Love Me Tomorrow? - Shirelles, The",
  "613 He Wasn't Man Enough - Toni Braxton",
  "614 Just My Imagination (Running Away With Me) - Temptations, The",
  "615 Breaking Up Is Hard To Do - Neil Sedaka",
  "616 I Wanna Dance With Somebody (Who Loves Me) - Whitney Houston",
  "617 Higher - Creed",
  "618 Dazzey Duks - Duice",
  "619 Nothing From Nothing - Billy Preston",
  "620 To Be With You - Mr. Big",
  "621 Born Free - Roger Williams",
  "622 Rock Me Amadeus - Falco",
  "623 9 To 5 - Dolly Parton",
  "624 Adia - Sarah McLachlan",
  "625 Return Of The Mack - Mark Morrison",
  "626 The Lion Sleeps Tonight - Tokens, The",
  "627 Get Outta My Dreams, Get Into My Car - Billy Ocean",
  "628 Shout - Tears For Fears",
  "629 Half-Breed - Cher",
  "630 Raise Your Glass - P!nk",
  "631 In The End - Linkin Park",
  "632 Blurry - Puddle Of Mudd",
  "633 Stereo Hearts - Gym Class Heroes",
  "634 Stuck On You - Elvis Presley",
  "635 Bad Romance - Lady GaGa",
  "636 Walk Like A Man - 4 Seasons, The",
  "637 Let's Hang On - Four Seasons, The",
  "638 Release Me - Wilson Phillips",
  "639 Right Thurr - Chingy",
  "640 The Night The Lights Went Out In Georgia - Vicki Lawrence",
  "641 Surfin' U.S.A. - Beach Boys, The",
  "642 Tighten Up - Archie Bell & The Drells",
  "643 Get Off Of My Cloud - Rolling Stones, The",
  "644 DJ Got Us Fallin' In Love - Usher",
  "645 All For You - Janet",
  "646 If You Leave Me Now - Chicago",
  "647 Jumpin' Jumpin' - Destiny's Child",
  "648 Caribbean Queen (No More Love On The Run) - Billy Ocean",
  "649 The Joker - Steve Miller Band",
  "650 Please Don't Go - K.C and the Sunshine Band",
  "651 Freak Me - Silk",
  "652 Everybody Loves Somebody - Dean Martin",
  "653 Drop It Like It's Hot - Snoop Dogg",
  "654 If I Can't Have You - Yvonne Elliman",
  "655 Power Of Love - Huey Lewis & The News",
  "656 She Works Hard For The Money - Donna Summer",
  "657 Waiting For A Girl Like You - Foreigner",
  "658 I'm Leaving It Up To You - Dale & Grace",
  "659 Best Of My Love - Eagles",
  "660 Under The Bridge - Red Hot Chili Peppers",
  "661 Toy Soldiers - Martika",
  "662 Duke Of Earl - Duke Of Earl (Gene Chandler)",
  "663 Blame It On The Rain - Milli Vanilli",
  "664 Bump N' Grind - R. Kelly",
  "665 You Can't Hurry Love - Supremes, The",
  "666 Just A Kiss - Lady Antebellum",
  "667 (Your Love Has Lifted Me) Higher And Higher - Rita Coolidge",
  "668 You Make Me Feel Brand New - Stylistics, The",
  "669 Y.M.C.A. - Village People",
  "670 Hard To Say I'm Sorry - Chicago",
  "671 Hold On - En Vogue",
  "672 Surf City - Jan & Dean",
  "673 A Woman Needs Love (Just Like You Do) - Ray Parker Jr.",
  "674 The Way It Is - Bruce Hornsby",
  "675 Love Theme From Romeo & Juliet - Henry Mancini, His Orchestra And Chorus",
  "676 Wannabe - Spice Girls, The",
  "677 Buy U A Drank (Shawty Snappin') - T-Pain",
  "678 Name - Goo Goo Dolls",
  "679 There'll Be Sad Songs (To Make You Cry) - Billy Ocean",
  "680 When I Think Of You - Janet Jackson",
  "681 Kokomo - Beach Boys, The",
  "682 My Love Is Your Love - Whitney Houston",
  "683 Say It Right - Nelly Furtado",
  "684 Karma Chameleon - Culture Club",
  "685 Tears In Heaven - Eric Clapton",
  "686 Don't Know Much - Linda Ronstadt",
  "687 Incense And Peppermints - Strawberry Alarm Clock",
  "688 Can't Buy Me Love - Beatles, The",
  "689 Say My Name - Destiny's Child",
  "690 White Flag - Dido",
  "691 You Give Love A Bad Name - Bon Jovi",
  "692 If I Ever Fall In Love - Shai",
  "693 Do You Really Want To Hurt Me - Culture Club",
  "694 Blue Moon - Marcels, The",
  "695 Ring My Bell - Anita Ward",
  "696 Harden My Heart - Quarterflash",
  "697 50 Ways To Leave Your Lover - Paul Simon",
  "698 Have You Ever Really Loved A Woman? - Bryan Adams",
  "699 Rise - Herb Alpert",
  "700 Leaving on A Jet Plane - Peter, Paul and Mary",
  "701 The Loco-Motion - Grand Funk",
  "702 Kyrie - Mr. Mister",
  "703 Undercover Angel - Alan O'Day",
  "704 Rock Me Gently - Andy Kim",
  "705 Angie Baby - Helen Reddy",
  "706 Wichita Lineman - Glen Campbell",
  "707 Runaround Sue - Dion",
  "708 Shining Star - Earth, Wind & Fire",
  "709 Sleep Walk - Santo and Johnny",
  "710 The Happy Organ - Dave \"Baby\" Cortez",
  "711 If You Had My Love - Jennifer Lopez",
  "712 Wild Ones - Flo Rida",
  "713 Let's Hear It For The Boy - Deniece Williams",
  "714 Groovy Kind Of Love - Phil Collins",
  "715 Airplanes - B.o.B.",
  "716 Do Wah Diddy Diddy - Manfred Mann",
  "717 It's Still Rock And Roll To Me - Billy Joel",
  "718 Whatcha Say - Jason DeRulo",
  "719 Angel Of Mine - Monica",
  "720 Every Rose Has Its Thorn - Poison",
  "721 Coming Up - Paul McCartney",
  "722 One Headlight - Wallflowers",
  "723 Show Me Love - Robin S",
  "724 Personality - Lloyd Price",
  "725 I Heard It Through The Grapevine - Gladys Knight and the Pips",
  "726 Boogie Nights - Heatwave",
  "727 Last Train To Clarksville - Monkees, The",
  "728 Teardrops On My Guitar - Taylor Swift",
  "729 One More Try - George Michael",
  "730 This Diamond Ring - Gary Lewis and the Playboys",
  "731 Lately - Divine",
  "732 Try Again - Aaliyah",
  "733 Out Of Touch - Daryl Hall & John Oates",
  "734 My Heart Has A Mind Of Its Own - Connie Francis",
  "735 Java - Al (He's the King) Hirt",
  "736 What A Fool Believes - Doobie Brothers, The",
  "737 Hero - Enrique Iglesias",
  "738 Romantic - Karyn White",
  "739 California Dreamin' - Mamas and The Papas, The",
  "740 Maniac - Michael Sembello",
  "741 Key Largo - Bertie Higgins",
  "742 My Prerogative - Bobby Brown",
  "743 Private Eyes - Daryl Hall & John Oates",
  "744 F**kin' Perfect - P!nk",
  "745 Moon River - Henry Mancini, His Orchestra and Chorus",
  "746 Fergalicious - Fergie",
  "747 Being With You - Smokey Robinson",
  "748 Take Good Care Of My Baby - Bobby Vee",
  "749 Single Ladies (Put A Ring On It) - Beyonce",
  "750 Glamorous - Fergie",
  "751 Sugar, We're Goin' Down - Fall Out Boy",
  "752 A Hard Day's Night - Beatles, The",
  "753 Someday - Sugar Ray",
  "754 She Drives Me Crazy - Fine Young Cannibals",
  "755 What Hurts The Most - Rascal Flatts",
  "756 Ain't It Funny - Jennifer Lopez",
  "757 Sir Duke - Stevie Wonder",
  "758 Hold My Hand - Hootie & The Blowfish",
  "759 From A Distance - Bette Midler",
  "760 All Star - Smash Mouth",
  "761 Hungry Eyes - Eric Carmen",
  "762 Grease - Frankie Valli",
  "763 Playground In My Mind - Clint Holmes",
  "764 When A Man Loves A Woman - Percy Sledge",
  "765 You Needed Me - Anne Murray",
  "766 Me And Bobby McGee - Janis Joplin",
  "767 The Reflex - Duran Duran",
  "768 Escapade - Janet Jackson",
  "769 Hello, I Love You - Doors, The",
  "770 Bennie And The Jets - Elton John",
  "771 Twisted - Keith Sweat",
  "772 The Sounds Of Silence - Simon and Garfunkel",
  "773 Escape (The Pina Colada Song) - Rupert Holmes",
  "774 I Like It - Enrique Iglesias",
  "775 Take Me Home, Country Roads - John Denver",
  "776 Mr. Brightside - Killers, The",
  "777 Again - Janet Jackson",
  "778 Teen Angel - Mark Dinning",
  "779 Ballroom Blitz - Sweet",
  "780 Always - Bon Jovi",
  "781 I Adore Mi Amor - Color Me Badd",
  "782 Picture - Kid Rock",
  "783 I'd Do Anything For Love (But I Won't Do That) - Meat Loaf",
  "784 Always On Time - Ja Rule",
  "785 Dancing Queen - ABBA",
  "786 Underneath It All - No Doubt",
  "787 Misty Blue - Dorothy Moore",
  "788 Unbelievable - EMF",
  "789 Hanky Panky - Tommy James and the Shondells",
  "790 The Lady In Red - Chris DeBurgh",
  "791 Band Of Gold - Freda Payne",
  "792 Calcutta - Lawrence Welk",
  "793 I Write Sins Not Tragedies - Panic! At The Disco",
  "794 Primrose Lane - Jerry Wallace",
  "795 Chariots Of Fire - Titles - Vangelis",
  "796 My Ding-A-Ling - Chuck Berry",
  "797 I Am Woman - Helen Reddy",
  "798 Got My Mind Set On You - George Harrison",
  "799 U Remind Me - Usher",
  "800 You And I - Eddie Rabbitt",
  "801 The Stripper - David Rose and His Orchestra",
  "802 Without You - David Guetta",
  "803 You Got It All - Jets, The",
  "804 Don't Mess With My Man - Nivea",
  "805 Mercy - Kanye West",
  "806 Forever - Chris Brown",
  "807 Slow Motion - Juvenile",
  "808 Bohemian Rhapsody - Queen",
  "809 Take A Bow - Rihanna",
  "810 Can't Take My Eyes Off You - Frankie Valli",
  "811 No Air - Jordin Sparks",
  "812 Everything She Wants (Remix) - Wham!",
  "813 Mama Told Me (Not To Come) - Three Dog Night",
  "814 Want Ads - Honey Cone, The",
  "815 Because Of You - Kelly Clarkson",
  "816 Let's Stay Together - Al Green",
  "817 Always - Atlantic Starr",
  "818 In My Head - Jason DeRulo",
  "819 The Loco-Motion - Little Eva",
  "820 The First Cut Is The Deepest - Sheryl Crow",
  "821 Come On Over Baby (All I Want Is You) - Christina Aguilera",
  "822 Help Me, Rhonda - Beach Boys, The",
  "823 Let Me Blow Ya Mind - Eve",
  "824 The Middle - Jimmy Eat World",
  "825 Sweet Nothin's - Brenda Lee",
  "826 Men In Black - Will Smith",
  "827 The River Of Dreams - Billy Joel",
  "828 Everybody Talks - Neon Trees",
  "829 You Were On My Mind - We Five",
  "830 My Love - Petula Clark",
  "831 Everything Is Beautiful - Ray Stevens",
  "832 I Love Your Smile - Shanice",
  "833 I Kissed A Girl - Katy Perry",
  "834 Halo - Beyonce",
  "835 Crystal Blue Persuasion - Tommy James and the Shondells",
  "836 Hair - Cowsills, The",
  "837 Let's Groove - Earth, Wind & Fire",
  "838 St. Elmo's Fire (Man In Motion) - John Parr",
  "839 Georgy Girl - Seekers, The",
  "840 Love Fool - Cardigans, The",
  "841 Master Blaster (Jammin') - Stevie Wonder",
  "842 Lay Down Sally - Eric Clapton",
  "843 We've Only Just Begun - Carpenters",
  "844 I Wanna Love You - Akon",
  "845 Just A Dream - Nelly",
  "846 Too Much Heaven - Bee Gees",
  "847 Theme From Shaft - Isaac Hayes",
  "848 With You - Chris Brown",
  "849 I Think We're Alone Now - Tommy James and the Shondells",
  "850 Devil With A Blue Dress On & Good Golly Miss Molly - Mitch Ryder",
  "851 Can I Get A.. - Jay-Z",
  "852 I Want It That Way - Backstreet Boys, The",
  "853 Respect - Aretha Franklin",
  "854 Running Scared - Roy Orbison",
  "855 16 Candles - Crests, The",
  "856 Woman, Woman - Union Gap",
  "857 (Shake, Shake, Shake) Shake Your Booty - K.C and the Sunshine Band",
  "858 Suga Suga - Baby Bash",
  "859 Nuthin' But A \"G\" Thang - Dr. Dre",
  "860 Sometimes Love Just Ain't Enough - Patty Smyth",
  "861 Candy Shop - 50 Cent",
  "862 Set Fire To The Rain - Adele",
  "863 Grillz - Nelly",
  "864 If You Go - Jon Secada",
  "865 Theme From \"The Greatest American Hero\" (Believe It Or Not) - Joey Scarbury",
  "866 Gettin' Jiggy Wit It - Will Smith",
  "867 Be Without You - Mary J. Blige",
  "868 Just The Two Of Us - Grover Washington Jr.",
  "869 Hit 'Em Up Style (Oops!) - Blu Cantrell",
  "870 The Motto - Drake",
  "871 All The Man That I Need - Whitney Houston",
  "872 Monster Mash - Bobby (Boris) Pickett",
  "873 Just Can't Get Enough - Black Eyed Peas, The",
  "874 Tootsee Roll - 69 Boyz",
  "875 Separate Lives - Phil Collins",
  "876 Kiss - Prince",
  "877 Disco Inferno - 50 Cent",
  "878 All Out Of Love - Air Supply",
  "879 Whatta Man - Salt 'N Pepa",
  "880 Beautiful - Christina Aguilera",
  "881 These Boots Are Made For Walkin' - Nancy Sinatra",
  "882 Heaven - Bryan Adams",
  "883 No, No, No Part II - Destiny's Child",
  "884 Ironic - Alanis Morissette",
  "885 When Can I See You - Babyface",
  "886 Quarter To Three - Gary U.S. Bonds",
  "887 ABC - Jackson 5, The",
  "888 Temperature - Sean Paul",
  "889 Torn - Natalie Imbruglia",
  "890 Crazy - Gnarls Barkley",
  "891 Replay - Iyaz",
  "892 Saving Forever For You - Shanice",
  "893 Case Of The Ex (Whatcha Gonna Do) - Mya",
  "894 Hips Don't Lie - Shakira",
  "895 Crush - Jennifer Paige",
  "896 You Make Me Feel Like Dancing - Leo Sayer",
  "897 Can't Smile Without You - Barry Manilow",
  "898 Again - Lenny Kravitz",
  "899 My Sacrifice - Creed",
  "900 Sideshow - Blue Magic",
  "901 The House Of The Rising Sun - Animals, The",
  "902 Someday We'll Be Together - Diana Ross and the Supremes",
  "903 Show And Tell - Al Wilson",
  "904 Weak - SWV",
  "905 Pon de Replay - Rihanna",
  "906 The Climb - Miley Cyrus",
  "907 Tubthumping - Chumbawamba",
  "908 Before You Walk Out Of My Life - Monica",
  "909 Time After Time - Cyndi Lauper",
  "910 Gotta Travel On - Billy Grammer",
  "911 I'm The Only One - Melissa Etheridge",
  "912 My Girl - Temptations, The",
  "913 Good Lovin' - Young Rascals",
  "914 Real Love - Mary J. Blige",
  "915 One Less Bell To Answer - 5th Dimension, The",
  "916 Disco Duck (Part 1) - Rick Dees",
  "917 I Can't Go For That (No Can Do) - Daryl Hall & John Oates",
  "918 Mickey - Toni Basil",
  "919 Still - Commodores",
  "920 At This Moment (Live) - Billy Vera",
  "921 I Feel Fine - Beatles, The",
  "922 If You Don't Know Me By Now - Simply Red",
  "923 Slow Hand - Pointer Sisters",
  "924 You Sang To Me - Marc Anthony",
  "925 Achy Breaky Heart - Billy Ray Cyrus",
  "926 Get It On.. Tonite - Montell Jordan",
  "927 When You're In Love With A Beautiful Woman - Dr. Hook",
  "928 Hello Goodbye - Beatles, The",
  "929 Lead Me On - Maxine Nightingale",
  "930 Your Body Is A Wonderland - John Mayer",
  "931 Every Morning - Sugar Ray",
  "932 I'll Take You There - Staple Singers, The",
  "933 It's So Hard To Say Goodbye To Yesterday - Boyz II Men",
  "934 Daddy Don't You Walk So Fast - Wayne Newton",
  "935 Angel - Shaggy",
  "936 Gangsta Lovin' - Eve",
  "937 Thnks Fr Th Mmrs - Fall Out Boy",
  "938 Jive Talkin' - Bee Gees",
  "939 Right Round - Flo Rida",
  "940 Girls Just Want To Have Fun - Cyndi Lauper",
  "941 I Believe I Can Fly - R. Kelly",
  "942 Drive By - Train",
  "943 I Don't Have The Heart - James Ingram",
  "944 Naughty Girls (Need Love Too) - Samantha Fox",
  "945 Rump Shaker - Wreckx-N-Effect",
  "946 My Way - Usher",
  "947 Please Forgive Me - Bryan Adams",
  "948 Photograph - Nickelback",
  "949 Come Back When You Grow Up - Bobby Vee",
  "950 Walkin' On The Sun - Smash Mouth",
  "951 Ride Like The Wind - Christopher Cross",
  "952 (Hey Won't You Play) Another Somebody Done Somebody Wrong Song - B.J. Thomas",
  "953 Little Willy - Sweet, The",
  "954 Paint It, Black - Rolling Stones, The",
  "955 Makin' It - David Naughton",
  "956 Making Love Out Of Nothing At All - Air Supply",
  "957 Rag Doll - 4 Seasons, The",
  "958 Boogie Fever - Sylvers, The",
  "959 Starships - Nicki Minaj",
  "960 How We Do - Game, The",
  "961 It's All Coming Back To Me Now - Celine Dion",
  "962 Amos Moses - Jerry Reed",
  "963 Rockin' Pneumonia - Boogie Woogie Flu - Johnny Rivers",
  "964 It Will Rain - Bruno Mars",
  "965 Tainted Love - Soft Cell",
  "966 They Don't Know - Jon B.",
  "967 Heaven Is A Place On Earth - Belinda Carlisle",
  "968 Only Wanna Be With You - Hootie & The Blowfish",
  "969 Cooler Than Me - Mike Posner",
  "970 Afternoon Delight - Starland Vocal Band",
  "971 Little Bit O'Soul - Music Explosion, The",
  "972 Make It With You - Bread",
  "973 Brown Sugar - Rolling Stones, The",
  "974 Treat Her Like A Lady - Cornelius Brothers & Sister Rose",
  "975 Insensitive - Jann Arden",
  "976 Girl I'm Gonna Miss You - Milli Vanilli",
  "977 Always On My Mind - Willie Nelson",
  "978 Someday - Mariah Carey",
  "979 Love Shack - B-52's, The",
  "980 Let It Rock - Kevin Rudolf",
  "981 You Mean The World To Me - Toni Braxton",
  "982 Hotel California - Eagles",
  "983 Smack That - Akon",
  "984 I Can Help - Billy Swan",
  "985 Young Girl - Union Gap",
  "986 Deep Purple - Nino Tempo & April Stevens",
  "987 Where Have You Been - Rihanna",
  "988 Holding Back The Years - Simply Red",
  "989 TSOP (The Sound Of Philadelphia) - MFSB",
  "990 Mrs. Robinson - Simon and Garfunkel",
  "991 Harper Valley P.T.A. - Jeannie C. Riley",
  "992 Don't You Know - Della Reese",
  "993 Feel Good Inc. - Gorillaz",
  "994 Stutter - Joe",
  "995 Confessions Part II - Usher",
  "996 Knock You Down - Keri Hilson",
  "997 Na Na Hey Hey Kiss Him Goodbye - Steam",
  "998 Break Your Heart - Taio Cruz",
  "999 Makes Me Wonder - Maroon5",
  "1000 Build Me Up Buttercup - Foundations, The"
]

export default musics;
